### ISSUE TITLE
Rust fails to compile the fasthash accelerations

### ISSUE THREAD

**Issue by Mike404-source** [duino-coin/duino-coin#1799]
Both compiled and source versions of PC_Miner are not running. Both versions seem to "hang" on user verification and no config file is written. The generated url does produce good results when entered manually in a browser.

**Comment by KorryKatti** [comment]
I am getting a libducohash error too on the new release

**Comment by paolokk07** [comment]
I am also getting an libducohash error with the 4.1:


error[E0599]: no method named `add_class` found for reference `&pyo3::prelude::P                                                                                        yModule` in the current scope
  --> src/lib.rs:44:7
   |
44 |     m.add_class::<DUCOHasher>()?;
   |       ^^^^^^^^^ method not found in `&PyModule`

error[E0277]: the trait bound `&pyo3::prelude::PyModule: From<BoundRef<'_, '_, p                                                                                        yo3::prelude::PyModule>>` is not satisfied
  --> src/lib.rs:42:1
   |
42 | #[pymodule]
   | ^^^^^^^^^^^ the trait `From<BoundRef<'_, '_, pyo3::prelude::PyModule>>` is                                                                                         not implemented for `&pyo3::prelude::PyModule`, which is required by `BoundRef<'                                                                                        _, '_, pyo3::prelude::PyModule>: Into<_>`
   |
   = note: required for `BoundRef<'_, '_, pyo3::prelude::PyModule>` to implement                                                                                         `Into<&pyo3::prelude::PyModule>`
   = note: this error originates in the attribute macro `pymodule` (in Nightly b                                                                                        uilds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `ducohasher` (lib) due to 2 previous errors

**Comment by misterpk-thailand** [comment]
![Screenshot_20240623_114110_Chrome.jpg](https://github.com/revoxhere/duino-coin/assets/61966054/56653998-f452-4a48-a07d-1c50d789eacc)

Just to reaport after upgraded to 4.1 version, I'm using 10 ESP32 device, hashrate increase from around 8x to 9x KH/s and reject also increase.

**Comment by revoxhere** [comment]
Closing as a duplicate of https://github.com/revoxhere/duino-coin/issues/1766

**Comment by simeononsecurity** [comment]
This is preventing the docker container I made from being able to update.
For now I've removed it, so we'll have to deal without the fasthash. 
Please notify me when this is fixed. I'll try and monitor either way.

Possible fix is to hardcode the rust version. But I'll have to look into that when I have more time.

**Comment by seanganteng** [comment]
Same eror

**Comment by KosmicDaKerbal** [comment]
```
root@server-inspiron:/mnt/SysHDD/Applications/DuinoCoin/V4.1/libducohash# cargo build --release
   Compiling ducohasher v0.1.0 (/mnt/SysHDD/Applications/DuinoCoin/V4.1/libducohash)
error[E0599]: no method named `add_class` found for reference `&pyo3::types::PyModule` in the current scope
  --> src/lib.rs:44:7
   |
44 |     m.add_class::<DUCOHasher>()?;
   |       ^^^^^^^^^ method not found in `&PyModule`

error[E0277]: the trait bound `&pyo3::types::PyModule: From<BoundRef<'_, '_, pyo3::types::PyModule>>` is not satisfied
  --> src/lib.rs:42:1
   |
42 | #[pymodule]
   | ^^^^^^^^^^^ the trait `From<BoundRef<'_, '_, pyo3::types::PyModule>>` is not implemented for `&pyo3::types::PyModule`, which is required by `BoundRef<'_, '_, pyo3::types::PyModule>: Into<_>`
   |
   = note: required for `BoundRef<'_, '_, pyo3::types::PyModule>` to implement `Into<&pyo3::types::PyModule>`
   = note: this error originates in the attribute macro `pymodule` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `ducohasher` (lib) due to 2 previous errors
```

**Comment by stijink** [comment]
+1

**Comment by LF1977** [comment]
Same error on Raspbery Pi 400 with latest Rasbian.

**Comment by profpandaa** [comment]
The compile time error should be fixed in https://github.com/profpandaa/compatible-libducohash

**Comment by revoxhere** [comment]
@profpandaa Nice job. I didn't have success reaching out to the original libducohash dev to take a look at it. Can I update the source code on server that miners download to your edit?

**Comment by profpandaa** [comment]
Of course!

**Comment by revoxhere** [comment]
Updated the codebase on server to version submitted by @profpandaa, this error should now be fixed.
